# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Pull Request Check - Backend

on:
  pull_request:
    types: [opened, synchronize]
    paths: 
      - 'server/**'
    branches:
      - master

jobs:
  PullRequestCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependency
        run: cd server && npm i
      - name: Dependency Integration
        run: cd server && npm ci
      - name: System Test
        run: cd server && npm test
